name: sphere-webbrick
vendor: Paul Cullender <@paulcull>
architecture: amd64
version: 0.0.1
icon: meta/null.svg
services:
- name: sphere-webbrick
  description: sphere-webbrick service
  start: ninja-shim ./sphere-webbrick
integration:
  sphere-webbrick:
    apparmor-profile: meta/sphere-webbrick.profile
